[versions]
aboutlibraries = "10.8.3"
activityCompose = "1.7.2"
agp = "8.1.0"
androidx-material = "1.5.0"
annotation = "1.6.0"
appcompat = "1.6.1"
compileSdk = "34"
com-android-application = "8.1.1"
com-android-library = "8.1.1"
constraintlayout = "2.1.4"
coreKtx = "1.10.1"
espressoCore = "3.5.1"
firebaseBom = "32.2.3"
foundation = "1.5.0"
foundationLayout = "1.5.0"
fragmentKtx = "1.7.0-alpha03"
googleServices = "4.3.15"
gson = "2.9.1"
holoColorPicker = "1.5"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlin = "1.9.0"
kotlinCompilerExtensionVersion = "1.5.2"
lifecycleLivedataKtx = "2.6.1"
material = "1.9.0"
minSdk = "28"
navigationFragmentKtx = "2.7.1"
playServicesAuth = "20.6.0"
roomRuntime = "2.5.2"
runtime = "1.5.0"
runtimeLivedata = "1.5.0"
spinkit = "1.4.0"
targetSdk = "34"
org-jetbrains-kotlin-android = "1.9.0"
ui = "1.5.0"
uiTestJunit4 = "1.5.0"
uiToolingPreview = "1.5.0"

[libraries]
aboutlibraries = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutlibraries" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "foundationLayout" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "androidx-material" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationFragmentKtx" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationFragmentKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomRuntime" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "uiTestJunit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTestJunit4" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
holoColorPicker = { module = "com.larswerkman:HoloColorPicker", version.ref = "holoColorPicker" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
spinKit = { module = "com.github.ybq:Android-SpinKit", version.ref = "spinkit" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-application" }
com-android-library = { id = "com.android.library", version.ref = "com-android-library" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }

[bundles]

